---
- name: installing apt-cacher-ng dependencies...
  become: yes
  become_user: root
  package:
    name:
      - apache2
      - apt-cacher-ng
    state: present

- name: install apt-cacher-ng config
  become: yes
  become_user: root
  with_items:
    - f: acng.conf
      d: /etc/apt-cacher-ng
      m: '0644'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'
